### ISSUE TITLE
i cant get search result after search

### ISSUE THREAD

**Issue by lee-jun-fan** [SAGARSURI/PixelPerfect#3]
onChanged: (value) {
                      bloc.changeQuery(value);
                    },

hi, can you explain about bloc.changeQuery(value) because it wont work after this line. i have added unplash api key also and i checked manually in browser of unplash url its working for my api key but i cant see result in app

**Comment by SAGARSURI** [comment]
Can you please add the github link to your app. I will check your code and provide you the fix. I suspect you are observing the stream in your UI. Check this:
`StreamBuilder(
                    stream: bloc.photosList,`

**Comment by SAGARSURI** [comment]
Closing it due to lack of response.
